### ISSUE TITLE
About the L1000 Similarity Matrices data

### ISSUE THREAD

**Issue by dahw0706** [MaayanLab/sigcom-lincs#60]
Hi, 

When we examined the data of **L1000 Gene-Gene Similarity Matrix** downloaded from **L1000 Similarity Matrices** section, it is noticed the value for the same gene is "0" in the matrix. For example, AKT1 to AKT1 = 0. 
![image](https://user-images.githubusercontent.com/109731133/184071158-873feb31-0566-4440-8224-014d3f598906.png)

If the value stands for signature similarity, it should be cosine and the value for the same gene in the matrix should be "1" instead of "0". Unless the value here stands for the reverse or 1-cosine. 

We didn't find the corresponding desrciption in the data or in the paper. It would be much appreciate if anyone can help to confirm the meaning of data in gene-gene similarity matrix. Thanks!

Best,
TJ

**Comment by sxie04** [comment]
Hi, thanks for the question. The gene-gene similarity matrix is indeed based on cosine similarity, and as such the diagonal would normally consists of 1s. We manually set the diagonal to 0 here because we have a specific implementation of a different tool that uses these matrices, where we did not want these self-interactions to be included. 
Apologies for any confusion, and please let me know if there are any more questions.

**Comment by dahw0706** [comment]
Hi, @sxie04 Thanks for your prompt explanation. It makes sense about the diagonal value as 0 now. We assumed the value in the matrix should be similarity (cosine) but just to confirm the meaning of the diagonal value. Again, thanks for the clarification!
